let files={'main.sglx':'# Welcome to Singulax\nsay("Hello from Singulax Studio!")\n'};let current='main.sglx', blockMode=false, blocks=[];const $=id=>document.getElementById(id);const editor=$('editor'), consoleEl=$('console'), canvas=$('game'),ctx=canvas.getContext('2d');
function renderFiles(){let s=$('fileSelect');s.innerHTML='';Object.keys(files).filter(x=>x.endsWith('.sglx')).forEach(f=>{let o=document.createElement('option');o.value=f;o.textContent=f;s.appendChild(o)});s.value=current;$('tree').innerHTML=Object.keys(files).filter(x=>x.endsWith('.sglx')).map(f=>`<div class="treefile ${f===current?'active':''}" onclick="openFile('${f}')">📄 ${f}</div>`).join('')}
function openFile(f){files[current]=editor.value;current=f;editor.value=files[f]||'';renderFiles()}
$('fileSelect').onchange=e=>openFile(e.target.value);
function newFile(){let n=prompt('New .sglx file name','script.sglx');if(!n)return;if(!n.endsWith('.sglx'))n+='.sglx';files[n]='';openFile(n)}
async function save(){files[current]=editor.value;let name=$('projectName').value;let r=await fetch('/api/project',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,files})});files=(await r.json()).files;renderFiles();consoleEl.textContent+='Saved.\n'}
async function run(){await save();consoleEl.textContent='Running '+current+'...\n';await fetch('/api/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('projectName').value,file:current,source:files[current]})});poll()}
async function stopRun(){await fetch('/api/stop',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('projectName').value})})}
async function poll(){let r=await fetch('/api/status?name='+encodeURIComponent($('projectName').value));let d=await r.json();if(d.output)consoleEl.textContent+=d.output;draw(d.frame);if(d.running)setTimeout(poll,100);else consoleEl.textContent+='\n[stopped]\n'}
function draw(cmds){ctx.clearRect(0,0,canvas.width,canvas.height);for(const c of cmds||[]){ctx.fillStyle=c.fill||'white';if(c.type==='rect')ctx.fillRect(c.x,c.y,c.w,c.h);if(c.type==='circle'){ctx.beginPath();ctx.arc(c.x,c.y,c.r,0,Math.PI*2);ctx.fill()}if(c.type==='text'){ctx.font=c.size+'px sans-serif';ctx.fillText(c.text,c.x,c.y)}}}
let keys={},buttons={};window.addEventListener('keydown',e=>{keys[e.key]=true});window.addEventListener('keyup',e=>{keys[e.key]=false});canvas.addEventListener('mousemove',e=>{let r=canvas.getBoundingClientRect();canvas.mx=(e.clientX-r.left)*canvas.width/r.width;canvas.my=(e.clientY-r.top)*canvas.height/r.height});canvas.addEventListener('mousedown',e=>{buttons[e.button===2?'right':'left']=true;sendInput({clicked:{[e.button===2?'right':'left']:true}})});canvas.addEventListener('mouseup',e=>{buttons[e.button===2?'right':'left']=false});setInterval(()=>sendInput({}),80);async function sendInput(extra){await fetch('/api/input',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.assign({name:$('projectName').value,keys,buttons,mouse_x:canvas.mx||0,mouse_y:canvas.my||0},extra))}).catch(()=>{})}
function toggleMode(){blockMode=!blockMode;$('codePane').hidden=blockMode;$('blocksPane').hidden=!blockMode;$('modeBtn').textContent=blockMode?'Code':'Blocks';if(blockMode){blocks=[];parseBlocks();renderBlocks()}else{files[current]=blocksToCode() ;editor.value=files[current]}}
function addBlock(type){blocks.push({type});renderBlocks()}
function parseBlocks(){blocks=[]}
function renderBlocks(){let box=$('blocks');box.innerHTML='';blocks.forEach((b,i)=>{let d=document.createElement('div');d.className='block';if(b.type==='say')d.innerHTML=`say <input data-i="${i}" value="${b.text||'Hello!'}">`;else if(b.type==='var')d.innerHTML=`variable <input data-i="${i}" value="${b.name||'x'}"> = <input data-v="${i}" value="${b.value||'0'}">`;else if(b.type==='if')d.innerHTML=`if <input data-c="${i}" value="${b.cond||'true'}"> then <input data-body="${i}" value="${b.body||'say("yes")'}"> end`;else if(b.type==='repeat')d.innerHTML=`repeat <input data-n="${i}" value="${b.n||'5'}"> times <input data-body="${i}" value="${b.body||'say("hi")'}"> end`;else if(b.type==='while')d.innerHTML=`while <input data-c="${i}" value="${b.cond||'true'}"> do <input data-body="${i}" value="${b.body||'break'}"> end`;else if(b.type==='forever')d.innerHTML=`forever do <input data-body="${i}" value="${b.body||'break'}"> end`;else if(b.type==='for')d.innerHTML=`for <input data-n="${i}" value="i"> = <input data-c="${i}" value="1, 10"> do <input data-body="${i}" value="say(i)"> end`;d.oninput=()=>{let els=d.querySelectorAll('input');if(b.type==='say')b.text=els[0].value;if(b.type==='var'){b.name=els[0].value;b.value=els[1].value}if(['if','while'].includes(b.type))b.cond=els[0].value,b.body=els[1].value;if(['repeat','forever'].includes(b.type))b.n=els[0]?.value,b.body=els[b.type==='repeat'?1:0].value;if(b.type==='for')b.name=els[0].value,b.range=els[1].value,b.body=els[2].value};box.appendChild(d)})}
function blocksToCode(){return blocks.map(b=>{if(b.type==='say')return `say(${JSON.stringify(b.text||'Hello!')})`;if(b.type==='var')return `local ${b.name||'x'} = ${b.value||'0'}`;if(b.type==='if')return `if ${b.cond||'true'} then\n  ${b.body||'say("yes")'}\nend`;if(b.type==='repeat')return `repeat ${b.n||5} times\n  ${b.body||'say("hi")'}\nend`;if(b.type==='while')return `while ${b.cond||'true'} do\n  ${b.body||'break'}\nend`;if(b.type==='forever')return `forever do\n  ${b.body||'break'}\nend`;if(b.type==='for')return `for ${b.name||'i'} = ${b.range||'1, 10'} do\n  ${b.body||'say(i)'}\nend`;return ''}).join('\n\n')+'\n'}
async function exportProject(){await save();location.href='/api/export?name='+encodeURIComponent($('projectName').value)}
async function importProject(e){let f=e.target.files[0];if(!f)return;let buf=await f.arrayBuffer(),bytes=new Uint8Array(buf),bin='';for(let i=0;i<bytes.length;i+=8192)bin+=String.fromCharCode(...bytes.subarray(i,i+8192));let name=prompt('Project name','ImportedProject')||'ImportedProject';let r=await fetch('/api/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,zip:btoa(bin)})});let d=await r.json();$('projectName').value=d.name;files=d.files;current=Object.keys(files).find(x=>x.endsWith('.sglx'))||'main.sglx';editor.value=files[current]||'';renderFiles()}
editor.addEventListener('input',()=>files[current]=editor.value);renderFiles();editor.value=files[current];
